### PR TITLE
Breaking: In error message, do not prefix the field name.

### PR DESCRIPTION
**Pull request by marcinkoziej**
This information is already in path list

### CODE REVIEW

**Comment by tttp** [comment]
@marcinkoziej fixed

https://github.com/fixthestatusquo/proca/commit/562988bc8e8ebfef4ae157a2a81a2e6d7ee99f06

**Comment by marcinkoziej** [comment]
@tttp does Campax need to regenerate? Do they use the widget from our server or a copy? They need to be notified in that case.

**Comment by tttp** [comment]
yeah, we are working on it

**Comment by marcinkoziej** [comment]
Ok let me know!

**Pull request merged**
