### PR TITLE
WIP: Message to Target model proposal

### PR DESCRIPTION
**Pull request by marcinkoziej**
This is a Work in Progress PR for Message To Target

## Model

Proposed data model:
```
Action <-> Message <-many-to-many-> Target 
                         MTT 
```
See the commit for Message, MTT schemas.

## API:

We add to ActionInput type:
- field `message` of type ActionMessageInput
  - subject string
  - body string
  - targets list of uuids of targets
  
If given, the Action has an associated Message record, connected to Targets.

## Sender

The sender is a genserver that scans unsent messages and sends them in a schedule.

### Schedule:

1.campaign has new fields: mtt_start and mtt_end type DATE which specify when the emails must be sent: 

`mtt_start <= date_sent < mtt_end`

2. the algorithm to send should work as follows

Within days in which we are sending, we want to send out same number of messages each day. This number can increase if we are still getting new messages after the `mtt_start` date. Example: it's day 3 of mtt action, we have still 5 days to go. We have 200 messages, so each of remaining day we will send 200 / 5 = 40 messages.

On which hour do we send the message? We want to target the day hours but because we have no idea about the timezone of target / action, it makes sense to use the action.inserted time as a heuristic, and send the message in the same hour as it was created, even if it's on a different day. So all the messages sent at 4pm will be sent at 4pm on different days between action start and end.

```
IF Today < mtt_start THEN EXIT
Unsent = all unsent messages
Send = all already sent messages
All = Unsent + Sent
Hour = current hour (as number)
RemainingDays mtt_end - Today
UnsentForHour = SELECT FROM Unsent u where date_trunc(HOUR, u.inserted_at) = Hour
UnsentForHourToday = UnsentForHour / RemainingDays

Send DistributeEvenly(UnsentForHourToday, 60 minutes)
```

### CODE REVIEW

**Comment by hiemanshu** [comment]
> On which hour do we send the message? We want to target the day hours but because we have no idea about the timezone of target / action, it makes sense to use the action.inserted time as a heuristic, and send the message in the same hour as it was created, even if it's on a different day. So all the messages sent at 4pm will be sent at 4m on different days between action start and end.

Would it make sense to send a certain amount of messages every hour around the time the action was taken? So if there aren't that many messages sent today, we can send a message within 30 mins of the action, or if it's crossed the limit, we can do it the next day around that hour?

**Comment by marcinkoziej** [comment]
> Would it make sense to send a certain amount of messages every hour around the time the action was taken? So if there aren't that many messages sent today, we can send a message within 30 mins of the action, or if it's crossed the limit, we can do it the next day around that hour?

This is what I am proposing. 
Note there is no one "action time", every action taken has its own time, so we have a distribution.
My algorithm is to:
- keep the hourly distortion within the day
- but change the daily distribution to be uniform across period we deliver mtts

**Comment by tttp** [comment]
I'm not sure I understand the aim of that. What is the benefit? On the con side: it's complicated to communicate to campaigners and explain

Isn't it easier to do it based on the target?
eg their office is opened from 9am to 5pm,  let's send emails between 8am to 6am?

**Comment by tttp** [comment]
> We want to target the day hours but because we have no idea about the timezone of target / action

we can simply ask the campaigners and save it part of the campaign (send between x and y, week-end yes/no) ?

**Comment by marcinkoziej** [comment]
@hiemanshu whats the status of this work?

**Comment by marcinkoziej** [comment]
@hiemanshu ah just noticed that `targets` query returns targets emails, it should not leak them.

**Pull request merged**
