### PR TITLE
Prevent sending multiple reminders

### PR DESCRIPTION
**Pull request by 1v4n4**
I added a check for "done" records, basically the same as for the action records. Maybe it is to many try/catches, but I don't know how to make it look better.

It works, if confirmed action gets to the queue, a new action record wouldn't be created.

I had to add two dependencies to run it locally, dotenv and "@types/minimist".

### CODE REVIEW

**Comment by marcinkoziej** [comment]
@1v4n4 can you refactor it using a helper function i made:

you can do now:
```
    const _payload =  await nullIfNotFound(db.get('action-' + action.actionId));
```

and _payload will be null if it's not found - so it won't introduce the try { } catch syntax which makes it complex

**Comment by marcinkoziej** [comment]
and please resolve the conflict with main

**Comment by 1v4n4** [comment]
@marcinkoziej I made some organization changes, check if ok: 
- extracted types to types.ts file
-  moved nullIfNotFound to helper.ts

There was a type issue:
`Function lacks ending return statement and return type does not include 'undefined'.
16 export const nullIfNotFound = async <T>(promise : Promise<T>) : Promise<T | null> => {`                                                 
I changed 'null' to 'any' (of course), not sure if it is the best thing to do here https://github.com/fixthestatusquo/proca-server/blob/f871663c343260faced0313820d684d502eba86e/service/confirm-reminder/src/helpers.ts#L16

**Comment by marcinkoziej** [comment]
> There was a type issue:
Function lacks ending return statement and return type does not include 'undefined'. 16 export const nullIfNotFound = async <T>(promise : Promise<T>) : Promise<T | null> => {
I changed 'null' to 'any' (of course), not sure if it is the best thing to do here 

@1v4n4 actually this was a helpful message! there was no "return v" to return the item when it _was_ found!
I've added it . The type should be T | null because it;'s either fetched item or null for "not found"

**Comment by marcinkoziej** [comment]
Hmm Damn, it does not work

```
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: New confirm  1989084
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: New confirm  1989116
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: New confirm  1989196
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: New confirm  1989252
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: New confirm  1989265
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: node:internal/process/promises:288
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:             triggerUncaughtException(err, true /* fromPromise */);
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:             ^
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: Error: NotFound:
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: Emitted 'error' event on Job instance at:
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:     at /opt/nvm/versions/node/v18.1.0/lib/node_modules/@proca/confirm-reminder/node_modules/node-schedule/lib/Invocation.js:277:17
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:   code: 'LEVEL_NOT_FOUND',
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:   notFound: true,
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]:   status: 404
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: }
gru 15 15:27:01 steinem.fixthestatusquo.org nvm-exec[2847343]: Node.js v18.1.0
gru 15 15:27:01 steinem.fixthestatusquo.org systemd[1]: confirm-reminder-lobbycontrol.service: Main process exited, code=exited, status=1/F
````

I get this on production. Can you run this on your test setup with the helper ?

**Comment by 1v4n4** [comment]
I will.
I chose not to return found item because we don't need it, but I guess it is better to return something than to fix the error by adding any type :)

**Comment by marcinkoziej** [comment]
> I chose not to return found item because we don't need it, but I guess it is better to return something than to fix the error by adding any type :)

OH! I would use the helper also when i want to get the item!!!
That would be surprising if it did not

**Pull request merged**
