### PR TITLE
Add support for handling mailjet webhooks

### PR DESCRIPTION
**Pull request by hiemanshu**

### CODE REVIEW

**Comment by marcinkoziej** [comment]
@hiemanshu I have an idea that would require to re-name the bounce reason, maybe.

I was thinking about how to handle the double opt in in Proca, the type of double opt in that does not make the action valid or rejected, but only adds one more bit of information to the consent.

Right now the processing works as follows:
```
      1                     2                            3                                  4
(new action) --> (supporter confirms email) --> (action confirmed by moderators) --> (action delivery)     (?)
                              v                             v                           v       v       v   ^
                    email sent to supporter            some mechanism                 CRM, webhook, TYEmail |
                             ^                                                                              |
                             `- double opt in type A                                                        |
                                                                                      double opt in type B -'
```

The basic action processing follows the "distribute" pattern where new action at step 1 is fast-forwarded to stage 4 where it's data is sent to (all at once) CRM, thank you email sender, webhook or whatever we want to do with the action to "deliver" it.

There are two optional stops on the way: Stage 2 will hold the action and send email to supporter, so they can confirm the action (or reject it), and at the same time confirm their consents (whatever checkboxes they clicked). I call it _double opt in type A._ 
Then, there can be another stop at stage 3: an email or slack message is sent to the team to approve the action (eg. signatures under open letter, that need to be moderated to stop trolls from appearing as signatories).

However, there is another type of double opt in - _type B_ - which does not affect the processing of the action. The action is processed and delivered to CRM, and then maybe the supporter clicks the email link they got, to add a double opt in to their consent.

That really got me thinking - how to model that?
 - Should the type B add a dblOptIn flat to Supporter or Contact and move action back to deliver stage 4, so CRM gets an updated action with just dblOptIn different? That would not be great, because of such double delivery, i can imagine even some CRMs just creating two actions. Also, that would make Proca do the delivery stage in whole, so it would also send the thank you email again, which sucks (or, we would have to detect what "kind" of stage 4 is this, ugly.
 - So i thought - perhaps this is a different kind of message/ notification to the Org CRM: just like Mailjet webhook, we send a small event containing the contactRef and status "dbl_opt_in" to the CRM. It's not sending the action again, just an event, perhaps to a separate API path. Perhaps good?
 - And then I thought - wait, we already have such mechanism, with BounceReason - depending on _what happens to email_, we change it's status. And we actually should also notify the CRM about this! If proca knows that a thank you email bounced, tell the CRM so the CRM does send a mailing to that email.
 - I then noticed that double opt in and bounce are events of similar class, and are also exclusive. It can either be double opt in, or bounce, or spam, not any two together. So perhaps the BounceReason should be renamed to EmailStatus with enum of: none, dbl_opt_in, spam, bounce - and we send a new kind of message into the delivery queue - to inform about changes of someones email status.

Thoughts?

**Comment by hiemanshu** [comment]
I think there's quite a lot to unpack here. Not just accounting for email status, but also action status, because an action can be rejected if email is bounce or spam as well. In these scenarios I think that might not have an effect on it. If we just mark action as confirmed, the reject function will auto fail, but I'm not sure if that's the optimal behavior here. 

As for what happens to the supporter, I think renaming it to EmailStatus just for Supporter makes sense, because to the CRM, you wanna send only what happened to the supporter, if the double opt-in is complete, the status is sent as such, and if it's a bounce / spam, the status can be stored as such. Is there ever going be a scenario of no double opt ins? For example, you send an email, and that email is sent, and there is no bounce, do we assume that the supporter is now "confirmed"? 

Since we don't have an opt-in mechanism for the Targets, it should have no effect on that.

**Comment by marcinkoziej** [comment]
- Agree that Target will never "opt in"; but the enum is also called BounceReason right? So I'd rather change it to EmailStatus to use same enum in both supporter and target, instead of having two enums that mostly overlap
- 
- email_status vs processing_status -> there is some interaction: 
  1. indeed a confirming supporter_status, when there is a bounce, should be changed to rejected. 
  2. But I would not change the delivered status of an action to rejected if the email bounces (i'd say we don't care here, we didn't want to verify here. Eg with a donation, we do not want to mark the action as rejected because TY email bounced.. if the donation was still done the action is OK).
  3. generally i would understand email_status as "can this person be sent a newsletter or not"  (also considering consent)
- " Is there ever going be a scenario of no double opt ins" - yes could be! we could send TY email and then email_status should stay "none" - the neutral value. It could be renamed because now email_status=none is confusing. "no_error" seems to express this. Or "mailable"? :thinking: 
- The other option is to leave bounce_reason, and add a dbl_opt_in BOOLEAN; but when we would be sending the events about email status to the CRM, the structure would look same for either bounce or dbl_opt_in, eg:
```
{schema: "proca:email:2", contact: {contactRef: "XXXXX"}, emailStatus: "optin" | "bounce" | "spam"}
``` 
And I guess not:
```
{schema: "proca:email:2", contact: {contactRef: "XXXXX"}, emailOptIn: true | false, bounceStatus: null | "bounce" | "spam"}
```

So if the event would merge the two aspects, maybe just one enum is ok?

**Comment by marcinkoziej** [comment]
Other issue:
please add the timestamp when the bounce_status/email_status was updated.

**Comment by hiemanshu** [comment]
> Agree that Target will never "opt in"; but the enum is also called BounceReason right? So I'd rather change it to EmailStatus to use same enum in both supporter and target, instead of having two enums that mostly overlap

Is processing status used for anything else? Can we use that to act as `opted-in` ? 

> But I would not change the delivered status of an action to rejected if the email bounces (i'd say we don't care here, we didn't want to verify here. Eg with a donation, we do not want to mark the action as rejected because TY email bounced.. if the donation was still done the action is OK).

What happens in case of a signature? What it becomes a problem with loads of bots signing up? Or Trolls?

>  please add the timestamp when the bounce_status/email_status was updated.

Add a new field for this?

**Comment by marcinkoziej** [comment]
Agree that Target will never "opt in"; but the enum is also called BounceReason right? So I'd rather change it to EmailStatus to use same enum in both supporter and target, instead of having two enums that mostly overlap

**Is processing status used for anything else? Can we use that to act as opted-in ?**

no we can't
`processing_status` of supporter and action is about processing pipeline, and has almost nothing to do with consents.
`contacts table` is about consents and all necessary for GDPR PII processing 
`email_status` is about deliverability (and also GDPR aspect of sending emails)

    But I would not change the delivered status of an action to rejected if the email bounces (i'd say we don't care here, we didn't want to verify here. Eg with a donation, we do not want to mark the action as rejected because TY email bounced.. if the donation was still done the action is OK).

**What happens in case of a signature? What it becomes a problem with loads of bots signing up? Or Trolls?**
I would say let the recipient decide - they will get all the info.

    please add the timestamp when the bounce_status/email_status was updated.

**Add a new field for this?**

yes please!

**Comment by hiemanshu** [comment]
Alright. Then I'll change it to `EmailStatus`. With:

`none`: Meaning no info
`dbl_opt_in`: Meaning opt-in completed
`bounce`, `spam`, `unsub`, `blocked`: Status from Mailjet

And I'll add a `email_status_updated` timefield.

**Comment by tttp** [comment]
Can you call it double_optin? It is a pet issue of mine to avoid
abbreviation, especially if it is to save 2 chars in an enum 😜

**Comment by hiemanshu** [comment]
Updated PR.

**Comment by marcinkoziej** [comment]
>  It is a pet issue of mine to avoid abbreviation, especially if it is to save 2 chars in an enum 
Ok indeed!

**Pull request merged**
